### PR TITLE
Rename functions

### PR DESCRIPTION
**Pull request by sjewo**
Hi @rCarto, hi @Nowosad !

I created a new branch and renamed the cartogram function in order to
* make code completion more easy
* make the function names a little more distinguishable and meaningful

cartogram() is now cartogram_cont()
nc_cartogram() is now cartogram_ncont()
noc_cartogram() is now cartogram_noc()

The old functions will still work properly, but are not displayed in the help index

What do you think about this changes?

### CODE REVIEW

**Comment by Nowosad** [comment]
@sjewo - you are reading my mind - I thought about it today. 
One question:
- Isn't cartogram_dorling() not better than cartogram_noc()?

**Comment by sjewo** [comment]
@Nowosad : cartogram_dorling() would be all right for me. 
What do you think @rCarto ?

**Comment by rCarto** [comment]
Hi @sjewo and  @Nowosad, 
I think it is a good idea to change function names. I initially did not use dorling in the name of the function since other function were not named dougenik_cartogram nor olson_cartogram . 
Starting with cartogram_ is all right and keeping function naming consistent would be great. 


Since the API of `cartogram` is changing, what would you think about changing the `shp` parameter to a more format-neutral `x`?

**Comment by Nowosad** [comment]
I like the `shp` -> `x` idea.

**Comment by sjewo** [comment]
Thanks for your feedback!
I would suggest to use only one naming system for the functions:

```
cartogram_dougenik()
cartogram_olson()
cartogram_dorling()
```
or
```
cartogram_cont()
cartogram_ncont()
cartogram_noc()
```
Using names of paper authors gives nicer function names, but what do we do with multiple authors (like Dougenik et al.)?

I see no problem in changing `shp` to `x`. I'll change the new function.

Should we also change the "weights" parameter to accept vectors in addition to columns names?

**Comment by Nowosad** [comment]
Hm... regarding to the functions names - my idea was based on the descriptions of cartograms online (e.g. https://www.gislounge.com/area-cartograms-explored/ or https://gisgeography.com/cartogram-maps/). They often state three main types of cartogram and name them "Non-contiguous", "Contiguous", and "Dorling". However, if you want just one of the versions above, I would prefer the second one.

Moreover, I would not change the "weights" parameter to accept vectors.

**Comment by sjewo** [comment]
Hi everybody,
`shp` is now `x` 40a72b808d4d720c50cf654bab06e56dbd1462a1 .

@Nowosad if this nomenclature is widely used, I'm okay with it:
```
cartogram_cont()
cartogram_ncont()
cartogram_dorling()
```

**Comment by rCarto** [comment]
Hi, I would not change the "weights" parameter neither.  Ok for these new function names!

**Comment by sjewo** [comment]
Changes are now in master.

**Comment by Nowosad** [comment]
Great. I've updated this in [the geocompr book](https://geocompr.robinlovelace.net/adv-map.html#other-mapping-packages).
Please let me know when I will be on CRAN.

**Comment by sjewo** [comment]
I'll submit the package to CRAN today or tomorrow.

**Pull request merged**
